services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    tty: true
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port

    volumes:
      - ${NGINX_BASE_PATH}/data:/data
      - ${NGINX_BASE_PATH}/letsencrypt:/etc/letsencrypt

  mariadb:
    tty: true
    container_name: mariadb-localhost
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: mariadb:latest
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mariadb --user=${MYSQL_USER} --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
    restart: unless-stopped
    volumes:
      - ${MYSQL_CONF_PATH}:/etc/mysql/conf.d
      - ${MYSQL_DATA_PATH}:/var/lib/mysql

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    tty: true
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=2G

  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #POSTGRES_DB: mydb
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    #ports:
      #- "8080:80"
    depends_on:
      - postgresql
    volumes:
      - ${PGADMIN_DATA_PATH}:/var/lib/pgadmin


networks:
  default:
    name: nginx-proxy-network
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/24